// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_writertitle_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_writertitle_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202501041237151_mig_writertitle_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
